default_platform(:ios)

platform :ios do
  lane :upload_screenshots do
    api_key = app_store_connect_api_key(
      key_id: ENV.fetch("ASC_KEY_ID"),
      issuer_id: ENV.fetch("ASC_ISSUER_ID"),
      key_filepath: ENV.fetch("ASC_KEY_PATH", "#{Dir.home}/.appstoreconnect/private_keys/AuthKey_#{ENV.fetch('ASC_KEY_ID')}.p8")
    )

    upload_to_app_store(
      api_key: api_key,
      skip_binary_upload: true,
      skip_metadata: true,
      screenshots_path: "./fastlane/screenshots",
      overwrite_screenshots: true,
      submit_for_review: false,
      force: true,
      precheck_include_in_app_purchases: false
    )
  end
end
